### ISSUE TITLE
where's a makefile?

### ISSUE THREAD

**Issue by sokoow** [r-lyeh/bundle#19]
Hi,

Is this a command line utility or a library ? I'm missing a makefile somewhere, any plans of using one ?

**Comment by r-lyeh** [comment]
Bundle is a compression library meant to be embedded into another application (like a command-line archiver, a game, or a bigger application). You only need drop ´bundle.hpp´ and ´bundle.cpp´ into your sources.

For example, to compile the demo try:
```
g++ demo.cc bundle.cpp -std=c++11 -lpthread
```

If you are looking for a compression utility, you can use https://github.com/r-lyeh/bundler instead
(which is a compression tool that uses this very same compression library).

**Comment by redthing1** [comment]
> Hi,
> 
> Is this a command line utility or a library ? I'm missing a makefile somewhere, any plans of using one ?

https://github.com/redthing1/bundle/blob/master/Makefile
