### ISSUE TITLE
how to compile .bun and .zip

### ISSUE THREAD

**Issue by van861205** [r-lyeh/bundle#22]
Hi, I generated the bundle.dll and bundle.lib.  I want to use archive.bun or  archive.zip to write a file. 
But, the program report link error 2019. because could not find .bun & .zip in lib and dll.
My IDE is VS2017.

**Comment by r-lyeh** [comment]
You can choose two different fixes.

1. Add following line in any of your source files: `#pragma comment(lib, "bundle.lib")`. Then configure your IDE to search the `bundle.lib` file, in your project settings (similar to this image): 
![image](https://user-images.githubusercontent.com/35402248/56358466-f3a7b880-61de-11e9-8b2d-3f6aa34297e8.png)

1. Add bundle.h and bundle.cpp files to your solution.

Hope it helps.
