### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by eXpl0it3r** [r-lyeh/bundle#9]
When compiling bundle (with GCC) you'll get a lot of warnings. I simply wanted to know if you'd like to reduce these or just keep the "embedded" external library sources exactly the same?

**Comment by r-lyeh** [comment]
Hard to say as this is one of the compromises I make when amalgamating other sources. I would like to remove the warnings eventually but I do not want to be sync'ing all my changes with every external update either. I might try to remove warnings on older (stabler) libraries though (which are not going likely to change any futher).

**Comment by eXpl0it3r** [comment]
Okay, yeah it's a minor annoyance, especially if the warnings originate from for loops which use `int` instead of `std::size_t` or similar...

Otherwise, I really like the simplicity of things. In my opinion compression libraries design their APIs often way too complicated.

Feel free to close this issue. :wink:

**Comment by r-lyeh** [comment]
it's only a problem for the guys that compile warnings as errors. and they're quite a few. I will try to remove as many warnings as possible. thx for the feedback :)
